planning_pipelines:
  pipeline_names: ["ompl"]
plan_request_params:
  planner_id: ompl
  planning_attempts: 1
  planning_pipeline: ompl
  max_velocity_scaling_factor: 1.0
  max_acceleration_scaling_factor: 1.0

# planning_pipelines:
#   pipeline_names: ["ompl"]

# ompl:
#   planning_plugin: ompl_interface/OMPLPlanner
#   request_adapters: >-
#     default_planner_request_adapters/AddTimeParameterization
#     default_planner_request_adapters/ResolveConstraintFrames
#     default_planner_request_adapters/FixWorkspaceBounds
#     default_planner_request_adapters/FixStartStateBounds
#     default_planner_request_adapters/FixStartStateCollision
#     default_planner_request_adapters/FixStartStatePathConstraints
#   start_state_max_bounds_error: 0.1

# plan_request_params:
#   planner_id: RRTConnectkConfigDefault  # Hoặc bất kỳ planner nào mà bạn enable trong ompl_planning.yaml
#   planning_attempts: 1
#   planning_pipeline: ompl
#   max_velocity_scaling_factor: 1.0
#   max_acceleration_scaling_factor: 1.0
